"""Curated offline prompt presets and timeline direction recommendations."""

from __future__ import annotations


def _presets(rows: tuple[tuple[str, str], ...]) -> dict[str, str]:
    if len(rows) != 32:
        raise ValueError(f"A preset family must contain exactly 32 entries, got {len(rows)}")
    return dict(rows)


CREATIVE_BRIEF_PRESETS = _presets((
    ("Fashion Runway", "Create a fashion runway film in which the featured model confidently presents the selected wardrobe and accessories while moving through a visually coherent venue."),
    ("Sports Fashion Walk", "Create a sports-fashion campaign in which the featured model walks with runway confidence through an active athletic location while clearly presenting the outfit and bag."),
    ("Luxury Product Reveal", "Create a premium product-reveal film that introduces the hero product through controlled anticipation, tactile interaction and a final immaculate beauty view."),
    ("Beauty Portrait", "Create an intimate beauty portrait that preserves the subject's identity while revealing makeup, hair, skin texture and expression through elegant camera movement."),
    ("Streetwear Campaign", "Create an energetic streetwear campaign following the subject through a real urban environment with confident attitude, readable clothing details and contemporary rhythm."),
    ("Lifestyle Morning", "Create a warm lifestyle story that follows the subject through a natural morning routine and makes the featured products feel useful, desirable and authentic."),
    ("Travel Destination", "Create an aspirational travel film that introduces the subject, destination and local atmosphere through clear geographic progression and memorable hero moments."),
    ("Food Commercial", "Create an appetizing food commercial showing preparation, texture, serving and the final dish with believable steam, ingredients and tactile detail."),
    ("Beverage Refreshment", "Create a refreshing beverage commercial built around condensation, pouring, effervescence and a satisfying final product hold."),
    ("Automotive Hero", "Create a cinematic automotive film that presents the vehicle's design, movement and road presence while preserving exact body shape, paint and wheel details."),
    ("Technology Launch", "Create a precise technology launch film that reveals the device, demonstrates its real function and ends on a clear premium product statement."),
    ("Home Interior", "Create an inviting interior-design film that moves naturally through the space and highlights materials, light, furniture and practical human use."),
    ("Architecture Showcase", "Create an architectural showcase that establishes the building's environment, reveals its form and guides the viewer through key spatial relationships."),
    ("Fitness Motivation", "Create a motivational fitness film with one readable training progression, credible physical effort and a strong final achievement beat."),
    ("Dance Performance", "Create a dance film that preserves full-body choreography, musical timing and spatial continuity while building toward a memorable final pose."),
    ("Music Performance", "Create a performance film centered on the artist's presence, accurate instrument or vocal action and expressive synchronization with the music."),
    ("Corporate Brand Story", "Create a concise corporate brand story that connects people, process and outcome through credible workplace action and polished visual continuity."),
    ("Workshop Craft", "Create a tactile craft film showing the maker, tools, material transformation and finished object through clear cause-and-effect actions."),
    ("Educational Demonstration", "Create a clear educational demonstration that introduces the objective, shows each essential action in order and ends with the completed result."),
    ("Event Highlight", "Create a dynamic event highlight that establishes the venue, captures authentic participant energy and finishes on the defining celebratory moment."),
    ("Romantic Moment", "Create an understated romantic scene built from natural interaction, meaningful eye contact, environmental atmosphere and a gentle emotional resolution."),
    ("Family Memory", "Create a warm family-memory film with authentic shared activity, recognizable relationships and a sincere final group moment."),
    ("Pet Adventure", "Create a playful pet adventure with readable animal behavior, safe environmental interaction and a charming final reaction."),
    ("Nature Documentary", "Create a concise nature-documentary sequence that establishes habitat, follows one observable behavior and preserves realistic animal and environmental motion."),
    ("Fantasy Quest", "Create a cinematic fantasy quest that establishes the hero, magical objective and environmental stakes before ending on a decisive discovery."),
    ("Science Fiction Mission", "Create a grounded science-fiction mission with coherent technology, spatially readable action and a controlled climactic reveal."),
    ("Mystery Suspense", "Create a suspense sequence that plants a clear visual clue, increases uncertainty through camera and sound, and ends on a revealing final beat."),
    ("Comedy Beat", "Create a concise visual-comedy scene with clear setup, escalating action, readable reaction and a precisely timed punchline hold."),
    ("Action Chase", "Create a spatially coherent action chase with readable pursuit direction, escalating obstacles and one decisive finishing beat."),
    ("Transformation Before After", "Create a transformation film that clearly establishes the initial state, shows the motivated change and matches composition for a convincing final comparison."),
    ("Seasonal Celebration", "Create a festive seasonal campaign with recognizable decorations, shared activity, product integration and a warm final tableau."),
    ("Minimal Product Study", "Create a minimal product study focused on silhouette, material, function and precise motion, ending on a clean uninterrupted hero frame."),
))


VISUAL_STYLE_PRESETS = _presets((
    ("Photorealistic Commercial", "Photorealistic commercial cinematography, clean exposure, realistic materials, controlled contrast, natural skin texture and polished production lighting."),
    ("Premium Fashion Editorial", "Premium fashion-editorial imagery, refined wardrobe texture, elegant posing, directional soft light, restrained color grading and confident composition."),
    ("Sports Fashion Campaign", "High-energy sports-fashion campaign, crisp daylight, athletic movement, clean saturated color, realistic fabric physics and stabilized full-body framing."),
    ("Luxury Product Cinema", "Luxury product cinematography, precise highlights, deep controlled shadows, premium materials, slow deliberate motion and immaculate visual separation."),
    ("Natural Lifestyle", "Natural lifestyle realism, available daylight, relaxed performances, tactile environments, gentle handheld presence and authentic imperfections."),
    ("High-Key Studio", "High-key studio look, bright seamless background, soft wraparound illumination, low shadow density, clean color and catalogue-level clarity."),
    ("Low-Key Noir", "Low-key noir cinematography, hard motivated light, deep shadows, selective highlights, smoky depth and restrained monochromatic color."),
    ("Golden Hour", "Warm golden-hour sunlight, long soft shadows, luminous skin, gentle lens bloom, amber highlights and natural atmospheric depth."),
    ("Blue Hour", "Blue-hour ambience, cool environmental light, warm practical accents, soft silhouettes, subtle haze and calm cinematic contrast."),
    ("Neon Cyberpunk", "Neon cyberpunk city style, saturated magenta and cyan lighting, wet reflections, deep contrast, atmospheric haze and futuristic production design."),
    ("Retro 1980s", "1980s commercial style, bold color blocks, glossy highlights, soft diffusion, practical neon, subtle analog grain and energetic framing."),
    ("Retro 1990s", "1990s editorial realism, direct flash accents, slightly muted print color, candid attitude, textured grain and simple graphic composition."),
    ("Y2K Pop", "Y2K pop aesthetic, chrome accents, glossy pastel color, bright frontal lighting, playful confidence and polished music-video energy."),
    ("Bold Comic Ink", "Bold comic-book ink style, heavy linework, limited high-contrast palette, halftone texture, graphic speed lines and expressive panel composition."),
    ("Anime Cel", "Clean anime cel animation, decisive outlines, controlled cel shadows, expressive poses, vivid color design and stable character proportions."),
    ("Stylized 3D Animation", "Stylized 3D animation, clean modeled forms, soft global illumination, readable silhouettes, polished materials and physically coherent motion."),
    ("Claymation", "Handmade claymation style, tactile fingerprints, miniature sets, soft studio lighting, stepped stop-motion timing and charming material deformation."),
    ("Papercraft", "Layered papercraft aesthetic, cut-paper edges, folded shapes, shallow diorama depth, tactile shadows and deliberate stop-motion movement."),
    ("Watercolor", "Expressive watercolor animation, translucent pigment washes, textured paper, soft edge blooms, restrained linework and fluid atmospheric transitions."),
    ("Oil Painting", "Painterly oil-on-canvas style, visible brushwork, rich color layering, dramatic modeled light and coherent moving painted forms."),
    ("Hand-Drawn Pencil", "Hand-drawn pencil animation, visible graphite texture, loose construction lines, paper grain, restrained shading and expressive frame-to-frame motion."),
    ("Minimalist Product", "Minimalist product-ad style, uncluttered negative space, precise geometry, soft premium lighting, restrained palette and slow intentional motion."),
    ("Clean Corporate", "Modern corporate visual language, neutral balanced color, bright practical environments, composed camera movement and approachable professional performances."),
    ("Architectural Cinema", "Architectural cinematography, disciplined perspective, strong leading lines, measured camera travel, material detail and controlled human scale."),
    ("Dreamlike Surreal", "Dreamlike surreal realism, familiar subjects in subtly impossible space, soft atmospheric light, elegant visual metaphor and continuous believable motion."),
    ("Dark Fantasy", "Dark-fantasy cinema, ancient tactile environments, cold shadowed palette, motivated firelight, atmospheric particles and grounded dramatic movement."),
    ("Sci-Fi Industrial", "Industrial science-fiction style, functional machinery, metallic surfaces, volumetric utility light, cool restrained color and realistic mechanical motion."),
    ("Warm Family", "Warm family-commercial style, gentle natural light, welcoming color, sincere expressions, soft camera movement and comfortable lived-in environments."),
    ("Food Commercial", "Premium food-commercial macro realism, appetizing color, precise surface highlights, controlled steam and droplets, tactile motion and immaculate styling."),
    ("Beauty Campaign", "Beauty-campaign cinematography, flattering soft key light, accurate skin texture, elegant hair movement, refined color and clean facial detail."),
    ("Performance Music Video", "Performance-driven music-video style, rhythmic camera blocking, expressive lighting, bold composition, precise beat emphasis and strong visual continuity."),
    ("Vintage Film", "Vintage photochemical film look, organic grain, gentle halation, softened contrast, period color response, subtle gate weave and cinematic exposure."),
))


TRANSITION_STYLE_PRESETS = _presets((
    ("Hard Cut", "Use a clean hard cut at the exact cue with matched screen direction and uninterrupted action continuity."),
    ("Match Cut", "Match shape, composition, color or subject position across the cut so both shots connect as one visual idea."),
    ("Match-on-Action", "Cut during a clearly readable action and continue the same movement, speed and direction in the incoming shot."),
    ("Whip Pan", "End with a fast whip pan and begin the next shot in the same direction, using motion blur to hide the cut."),
    ("Cross Dissolve", "Use a restrained cross dissolve with aligned subject placement and a gradual atmospheric blend between shots."),
    ("Dip to Black", "Briefly dip through black, preserve continuing sound and reveal the next shot from the same narrative beat."),
    ("Dip to White", "Use a short luminous dip to white motivated by a bright source, then resolve smoothly into the next shot."),
    ("Fade Through Color", "Fade through a dominant scene color shared by both shots while preserving rhythm and visual orientation."),
    ("Luma Fade", "Transition according to image luminance, allowing highlights or shadows to reveal the incoming shot progressively."),
    ("Film Burn", "Use a brief organic film-burn flare that consumes the outgoing frame and exposes the incoming image without lingering."),
    ("Light Leak", "A motivated light leak sweeps across the lens, briefly obscures the frame and reveals the next shot beneath it."),
    ("Ink Wipe", "A graphic ink shape spreads across the outgoing image and retracts to reveal the next shot with tactile edges."),
    ("Paper Tear", "A physical paper-tear edge opens across the frame and exposes the next scene as a layered surface beneath it."),
    ("Page Turn", "The outgoing frame bends and turns like a page while the incoming shot remains spatially stable underneath."),
    ("Lens Flare Wipe", "A bright lens flare travels across frame and masks a seamless cut at peak intensity."),
    ("Object Wipe", "A foreground object fully crosses the lens and hides a cut to a matched object or movement in the next shot."),
    ("Foreground Occlusion", "Cut while the camera passes behind a wall, person or prop, maintaining identical camera direction after the occlusion."),
    ("Doorway Passage", "Move through a doorway or portal that naturally replaces the outgoing environment with the incoming scene."),
    ("Speed Ramp", "Accelerate the final movement into the cut and decelerate the matched incoming movement to normal speed."),
    ("Crash Zoom", "Use a rapid controlled zoom to a matching detail, then emerge from that detail in the incoming shot."),
    ("Spin Transition", "Rotate the camera around a stable center and hide the cut in directional rotational blur without disorienting geography."),
    ("Zoom Through", "Push through a clearly defined object or surface and continue the same forward camera path in the next environment."),
    ("Morph Match", "Morph only one matched subject or shape across the transition while keeping scale, position and lighting coherent."),
    ("Graphic Shape Wipe", "Use a clean designed geometric shape to cover the frame and reveal the next shot with exact timing."),
    ("Split-Screen Merge", "Introduce both shots in split screen, align their shared subject or horizon and merge into the incoming full frame."),
    ("Glitch", "Use a very brief controlled digital glitch at the cut; preserve subject identity and avoid persistent image corruption."),
    ("Pixel Dissolve", "Break the outgoing image into restrained pixels that reorganize into the incoming shot while maintaining silhouette readability."),
    ("Smoke Wipe", "A motivated layer of smoke crosses the lens and reveals the incoming scene through changing density."),
    ("Dust Burst", "A short physical dust burst masks the cut and settles naturally into the incoming environment."),
    ("Water Ripple", "A single water-ripple distortion expands across the image and resolves into the next shot without warping subjects afterward."),
    ("Rack-Focus Cut", "Rack focus onto a foreground or background detail and cut at maximum blur to a matched sharp detail in the next shot."),
    ("J-Cut / L-Cut", "Let the incoming sound begin before the visual cut or let outgoing sound continue after it, preserving natural audio continuity."),
))


CONSTRAINT_PRESETS = _presets((
    ("Identity Lock", "Preserve one consistent subject identity, facial structure, apparent age, hairstyle, skin appearance and recognizable features in every frame."),
    ("Full-Body Lock", "Keep the complete head, hair, arms, hands, torso, legs, ankles and both feet inside frame with visible space above and below."),
    ("Product Lock", "Preserve exactly one product instance with unchanged shape, proportions, color, material, hardware, construction and recognizable design."),
    ("Clothing Lock", "Keep every garment fitted to the same body area with stable color, pattern, seams, hem length, layering and realistic fabric physics."),
    ("Face Detail", "Maintain stable eyes, nose, mouth, teeth, ears and facial symmetry; prevent face drift, beautification drift and expression flicker."),
    ("Hand Accuracy", "Maintain anatomically correct hands and fingers with believable grip, contact, occlusion and object interaction."),
    ("Single Subject", "Show exactly one main subject; do not duplicate, replace, merge or introduce additional people or reflections that resemble another subject."),
    ("No Generated Text", "Do not generate captions, subtitles, labels, banners, interface elements, watermarks or new readable text."),
    ("Exact Text", "Preserve supplied visible wording exactly, including spelling, case, line order, placement and timing; do not add any other text."),
    ("Logo Stability", "Keep existing small product marks in their original placement and proportions; never invent, enlarge, duplicate or rewrite logos."),
    ("Environment Lock", "Preserve environment layout, horizon, architecture, surfaces, lighting direction, background depth and geographic continuity."),
    ("Geometry Lock", "Keep object geometry, straight lines, symmetry, perspective and structural connections stable across the sequence."),
    ("Color Lock", "Preserve established product, wardrobe, skin and environment colors without hue drift, flashing or unmotivated grading changes."),
    ("Lighting Lock", "Maintain one coherent lighting direction, exposure, shadow softness, reflections and color temperature throughout."),
    ("Camera Discipline", "Use only the specified camera path, speed and amplitude; prevent accidental zoom, shake, horizon roll and framing drift."),
    ("Motion Discipline", "Keep movement smooth, physically motivated and continuous; prevent teleportation, sliding feet, sudden speed changes and pose snapping."),
    ("Anatomy Lock", "Maintain realistic body proportions, joint articulation, limb count, gait, balance and contact with the ground."),
    ("Remove Background People", "Remove all people inherited from environment references and prevent new background pedestrians, players or crowds from appearing."),
    ("No Extra Objects", "Do not introduce unrelated props, accessories, vehicles, animals, furniture or environmental decorations."),
    ("Single Continuous Take", "Use one continuous take with no cuts, transitions, angle jumps, time jumps or discontinuous camera repositioning."),
    ("No Close-Ups", "Do not use face-only, bust, waist-up, product-only, macro or extreme close-up framing."),
    ("Lip-Sync Lock", "Synchronize visible mouth shapes precisely to the supplied dialogue while preserving the exact words, speaker identity and natural pauses."),
    ("Audio Continuity", "Maintain continuous ambience, room tone and sound perspective across shots without pops, abrupt level changes or unexplained silence."),
    ("Physical Contact", "Preserve accurate contact points, grip, weight, friction, gravity, momentum and collision response between subjects and objects."),
    ("Material Fidelity", "Preserve material roughness, gloss, translucency, weave, stitching, metal response and surface imperfections consistently."),
    ("Scale Lock", "Keep realistic and constant scale relationships between people, products, props and the environment."),
    ("Safe Frame Boundary", "Keep important faces, hands, products, feet and text away from frame edges and prevent accidental cropping."),
    ("Temporal Stability", "Prevent flicker, texture crawling, color pulsing, object popping, identity drift and frame-to-frame design changes."),
    ("Minimal Change", "Modify only the explicitly requested attributes and preserve all other referenced content and continuity unchanged."),
    ("Brand-Safe Output", "Avoid unrelated brands, competitor marks, offensive content, unsafe behavior and misleading product functionality."),
    ("Clean Delivery", "Do not generate borders, mattes, split screens, UI chrome, debug overlays, compression artifacts or unfinished frames."),
    ("Maximum Consistency", "Prioritize identity, anatomy, wardrobe, product, environment and lighting consistency over elaborate camera motion or small detail reveals."),
))


SOUNDSCAPE_PRESETS = _presets((
    ("Natural Outdoor", "Natural outdoor ambience with light wind, distant birds, subtle foliage movement and physically synchronized footsteps."),
    ("Tropical Court", "Soft tropical breeze through palm leaves, distant birds, shoe contact on the court and restrained equipment or clothing movement."),
    ("Urban Day", "Layered daytime city ambience with distant traffic, soft pedestrian presence, building reflections and close synchronized footsteps."),
    ("Urban Night", "Distant night traffic, low electrical hum, occasional tire movement, sparse city echoes and close physical Foley."),
    ("Quiet Interior", "Controlled indoor room tone, low ventilation hum, subtle cloth movement and precise close-range object Foley."),
    ("Luxury Showroom", "Quiet premium showroom ambience with soft air conditioning, restrained footsteps and delicate product-handling sounds."),
    ("Studio Silence", "Near-silent treated studio room tone with only precise subject movement, clothing and product Foley."),
    ("Office", "Low office room tone, distant keyboard activity, ventilation and subtle movement without intelligible background speech."),
    ("Café", "Soft café room tone, distant cups, restrained conversation murmur and gentle street ambience without clear background dialogue."),
    ("Home Interior", "Warm domestic room tone, light appliance hum, subtle floor contact and close natural movement sounds."),
    ("Forest", "Layered forest ambience with leaves, branches, birds, distant insects and grounded footsteps on natural terrain."),
    ("Beach", "Rhythmic shoreline waves, soft sea breeze, distant seabirds and footsteps interacting naturally with sand."),
    ("Rain", "Consistent rainfall on nearby surfaces, occasional runoff, dampened environmental reflections and synchronized wet footsteps."),
    ("Storm", "Strong wind, layered rain, distant thunder and responsive environmental rattles without overpowering primary action."),
    ("Snow", "Muted winter ambience, soft wind, compressed footsteps in snow and restrained clothing movement."),
    ("Desert", "Dry open-air wind, fine sand movement, sparse distant ambience and grounded footsteps on granular terrain."),
    ("Mountain", "Open mountain wind, distant birds, broad natural reflections and footsteps on rock or gravel."),
    ("Warehouse", "Large industrial room tone, distant mechanical hum, long reflections and weighty footsteps on concrete."),
    ("Factory", "Layered mechanical ambience, ventilation, restrained machinery cycles and close synchronized work sounds."),
    ("Sci-Fi Interior", "Low futuristic power hum, subtle interface tones, ventilation and precise mechanical movement without constant alarms."),
    ("Fantasy Forest", "Natural woodland ambience enhanced by sparse shimmering tones, moving leaves and distant nonverbal creatures."),
    ("Sports Arena", "Broad arena reflections, restrained distant crowd energy, floor or field contact and clear primary action Foley."),
    ("Tennis Match", "Court ambience with shoe squeaks, controlled ball impacts, racquet contact, light wind and distant nonverbal spectators."),
    ("Fashion Runway", "Measured footsteps, subtle fabric movement, restrained room reflections, distant camera shutters and no intelligible crowd speech."),
    ("Automotive", "Engine character, road and tire texture, aerodynamic wind and mechanical responses synchronized precisely to vehicle movement."),
    ("Food Preparation", "Detailed kitchen room tone with precise cutting, pouring, sizzling, utensil and surface-contact sounds."),
    ("Beauty Close-Up", "Near-silent studio ambience with delicate brush, skin, hair and product-container Foley."),
    ("ASMR Product", "Highly detailed close-mic material, tapping, sliding, opening and handling sounds with minimal background ambience."),
    ("Comic Action", "Exaggerated but synchronized impacts, whooshes and environmental reactions layered over a readable physical ambience."),
    ("Horror Atmosphere", "Sparse low room tone, distant structural creaks, restrained wind and close unsettling physical detail without musical scoring."),
    ("Dream Ambience", "Soft diffuse environmental tone, distant reversed textures, airy movement and gentle spatial echoes."),
    ("No Diegetic Sound", "N/A"),
))


MUSIC_PRESETS = _presets((
    ("No Music", "N/A"),
    ("Premium Ambient", "Restrained premium ambient score with soft synth pads, sparse piano accents, low pulse and no vocals."),
    ("Fashion Electronic", "Clean fashion-electronic beat around 100 BPM with restrained kick, soft bass, polished synth accents and no vocals."),
    ("Upbeat Pop Instrumental", "Bright upbeat pop instrumental around 115 BPM with crisp drums, warm bass, light guitar and no vocals."),
    ("Sports Energy", "Driving sports instrumental around 125 BPM with tight percussion, pulsing bass, bold synth rhythm and no vocals."),
    ("Luxury Minimal", "Slow luxury-minimal score with sparse piano, deep soft bass, subtle strings and generous negative space."),
    ("Corporate Optimistic", "Modern optimistic corporate instrumental with light percussion, muted guitar, warm synth and a gentle rise."),
    ("Acoustic Lifestyle", "Friendly acoustic instrumental with soft guitar, hand percussion, warm bass and no vocals."),
    ("Piano Emotional", "Intimate solo-piano theme at a slow tempo with natural dynamics and no additional vocals."),
    ("Cinematic Orchestra", "Cinematic orchestral score with restrained strings, low brass support, measured percussion and a controlled final resolve."),
    ("Epic Trailer", "Compressed epic trailer pulse with low strings, brass swells and large percussion, building toward one final accent."),
    ("Suspense Pulse", "Low suspense pulse with muted percussion, sub-bass movement, sparse high textures and no melodic resolution until the end."),
    ("Dark Ambient", "Dark ambient drones, low harmonic movement, sparse metallic texture and no vocals or obvious beat."),
    ("Horror Minimal", "Minimal horror score with dissonant strings, low pressure tones, sparse impacts and long controlled silence."),
    ("Dream Pop Instrumental", "Dream-pop instrumental with washed guitars, soft drums, warm bass and airy synth layers without vocals."),
    ("Lo-Fi Beat", "Relaxed lo-fi instrumental around 82 BPM with dusty drums, mellow keys, soft bass and subtle vinyl texture."),
    ("Jazz Lounge", "Refined lounge jazz with brushed drums, upright bass, restrained piano and no vocals."),
    ("Funk Groove", "Clean funk instrumental with syncopated bass, muted guitar, tight drums and bright restrained brass accents."),
    ("Disco Fashion", "Polished disco-fashion groove around 118 BPM with four-on-the-floor drums, elastic bass, strings and no vocals."),
    ("Synthwave", "Retro synthwave instrumental with analog arpeggios, gated drums, warm pads and a steady driving pulse."),
    ("Cyberpunk Industrial", "Dark cyberpunk-industrial rhythm with distorted percussion, mechanical bass, granular synth textures and no vocals."),
    ("Ambient Tech", "Minimal technology ambience with clean pulses, glassy synth notes, soft sub-bass and precise spacious production."),
    ("Hip-Hop Instrumental", "Confident hip-hop instrumental around 92 BPM with restrained drums, deep bass, sparse keys and no vocals."),
    ("Trap Instrumental", "Controlled trap instrumental with crisp hi-hats, deep sub-bass, sparse melodic texture and no vocals."),
    ("Latin Percussion", "Upbeat Latin-influenced instrumental with hand percussion, warm bass, light guitar and no vocals."),
    ("Tropical House", "Light tropical-house instrumental around 108 BPM with soft kick, marimba-like plucks, warm bass and no vocals."),
    ("Afrobeat Instrumental", "Bright Afrobeat-inspired instrumental with interlocking percussion, melodic bass, clean guitar and no vocals."),
    ("Rock Energy", "Energetic instrumental rock with tight drums, controlled electric guitars, supportive bass and no vocals."),
    ("Indie Film", "Understated indie-film score with felt piano, soft guitar, subtle percussion and an intimate unresolved warmth."),
    ("Children's Playful", "Playful light instrumental with pizzicato strings, woodwinds, soft percussion and no vocals."),
    ("Fantasy Orchestral", "Lyrical fantasy orchestral score with harp, woodwinds, warm strings and a gentle magical rise."),
    ("Meditative", "Slow meditative sound bed with sustained bowls, soft drones, breath-like texture and no rhythmic pulse or vocals."),
))


SHOT_RECOMMENDATIONS = {
    "Establishing Shot": {
        "subject_action": "The primary subject enters or settles into a clear readable starting position and establishes the scene objective.",
        "environment_response": "Background activity, practical light, weather and atmospheric depth establish the location without distracting from the subject.",
        "detail": "Begin with stable geography and readable screen direction; preserve enough negative space for the next action.",
    },
    "Hero Reveal": {
        "subject_action": "The subject turns or steps into the key light, reveals the defining face, wardrobe or product, and makes confident eye contact.",
        "environment_response": "Light, reflections and subtle atmospheric movement separate the subject as the reveal completes.",
        "detail": "Time the clearest identity and product reveal to the end of the camera move, then stabilize briefly.",
    },
    "Product Demonstration": {
        "subject_action": "The subject uses, wears, carries or presents the product according to its real function with accurate hand placement and believable weight.",
        "environment_response": "Contact shadows, reflections, fabric, straps and nearby lightweight elements respond naturally to the demonstration.",
        "detail": "Keep product identity, scale, material and attachment points stable; reveal details through action and camera angle rather than an abrupt crop.",
    },
    "Action Beat": {
        "subject_action": "The subject performs one clear motivated action with readable anticipation, execution and recovery.",
        "environment_response": "Dust, fabric, hair, props and practical elements react with physically accurate timing and restrained amplitude.",
        "detail": "Maintain screen direction, anatomy and contact throughout; avoid stacking multiple unrelated actions in the same beat.",
    },
    "Reaction Close-up": {
        "subject_action": "The subject registers the preceding event through a controlled eye movement, facial reaction and small posture change.",
        "environment_response": "Background motion and sound soften so the reaction remains the dominant readable event.",
        "detail": "Preserve facial identity and eyeline continuity; keep the reaction subtle enough to avoid expression drift.",
    },
    "Final Hero Shot": {
        "subject_action": "The subject completes the action, settles into a confident final pose and holds the defining identity or product clearly toward camera.",
        "environment_response": "Residual environmental motion gradually settles while lighting and reflections remain stable.",
        "detail": "Stop camera drift before the final frame and hold a clean composition long enough for a decisive ending.",
    },
}


MARKER_RECOMMENDATIONS = {
    "SFX Cue": "Place one precise synchronized physical sound at this cue; define its source, texture, distance, onset and decay.",
    "Music Cue": "Introduce, remove or reshape the score at this exact moment with a motivated change in instrumentation and intensity.",
    "Beat": "Align the strongest visible action, camera accent or edit point exactly to this musical beat without changing continuity.",
    "Camera Cue": "Begin or settle the specified camera movement at this cue while preserving framing, screen direction and subject priority.",
    "Dialogue Cue": "Begin the assigned speaker's exact line here with the specified language, delivery and lip-sync behavior.",
    "Ending Hold": "Settle into the final hero composition before this cue and hold identity, products, text and environment unchanged through the final frame.",
}


TRANSITION_RECOMMENDATIONS = {
    name: text for name, text in TRANSITION_STYLE_PRESETS.items()
}
